version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: pttk
      POSTGRES_PASSWORD: pttkht2025
      POSTGRES_DB: project
    ports:
      - "3457:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql

volumes:
  postgres_data:
