version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: pttk
      POSTGRES_PASSWORD: pttkht2025
      POSTGRES_DB: project
    ports:
      - "0704:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
